### PR TITLE
REL-2281: Updated icons for OT 2015B

### PR DESCRIPTION
**Pull request by cquiroz**
Just new versions of all the icons. It was tested on OSX

### CODE REVIEW

**Comment by swalker2m** [comment]
Usually there is accompanying text that explains what we're looking at in the splash screen.  Is that already there or coming?

**Comment by cquiroz** [comment]
Right, it is on the ticket, I think it goes in welcome.html?

**Comment by cquiroz** [comment]
Text was added

**Comment by swalker2m** [comment]
:+1:

**Pull request merged**
