### PR TITLE
REL-3842 - update PIT icons

### PR DESCRIPTION
**Pull request by tpolecat**
I don't really know how to check that they work. They seem ok. They look like this in the Finder. It draws a border around `.ico` files for some reason, that's not part of the image.

image

### CODE REVIEW

**Comment by cquiroz** [comment]
I think there is also a png used on the linux version as well, but it is not under app but as a resource in the pit module

**Comment by sraaphorst** [comment]
Yes, I believe that Carlos is right... I'll try to find the spot.

**Comment by sraaphorst** [comment]
It is here:

./bundle/edu.gemini.pit/src/main/resources/edu/gemini/pit/ui/util/icons/pit_icon.png

**Comment by sraaphorst** [comment]
It's 512x512 px, which I think is the size of the PNG that Bryan usually distributes?

**Comment by tpolecat** [comment]
Ah ok thanks.

**Comment by tpolecat** [comment]
Ok done

**Pull request merged**
