### PR TITLE
REL-3100: Fix Horizons lookups in PIT 2017B.

### PR DESCRIPTION
**Pull request by sraaphorst**

### CODE REVIEW

**Comment by cquiroz** [comment]
Is this the same change as #1198 ?

**Comment by sraaphorst** [comment]
@cquiroz Yes, it should be identical 😸

**Comment by sraaphorst** [comment]
I will build the PITs after this and then promote to develop.

**Comment by cquiroz** [comment]
Ok, I checked the contents of the keystore and it contains the 4 we need

```
Your keystore contains 4 entries

digicertroot, Mar 28, 2017, trustedCertEntry,
Certificate fingerprint (SHA1): 5F:B7:EE:06:33:E2:59:DB:AD:0C:4C:9A:E6:D3:8F:1A:61:C7:DC:25
letsencrypt-inter, Feb 28, 2017, trustedCertEntry,
Certificate fingerprint (SHA1): E6:A3:B4:5B:06:2D:50:9B:33:82:28:2D:19:6E:FE:97:D5:95:6C:CB
gemini, Jun 20, 2013, trustedCertEntry,
Certificate fingerprint (SHA1): 04:E7:81:2E:9A:26:7D:7D:D8:46:7A:6F:F4:F9:E1:E1:8A:1B:97:A9
digicertsha2, Mar 28, 2017, trustedCertEntry,
Certificate fingerprint (SHA1): 7E:2F:3A:4F:8F:E8:FA:8A:57:30:AE:CA:02:96:96:63:7E:98:6F:3F
```

**Comment by sraaphorst** [comment]
Oooops... @cquiroz, this contains the GN AGS server key?
I forgot to ask, but we need that.

**Comment by cquiroz** [comment]
it is there, letsencrypt is the external ags cert

**Pull request merged**
