### PR TITLE
REL-2334-B: Fix OT Position Editor color map and intensity options

### PR DESCRIPTION
**Pull request by cquiroz**
The previous PR fixed the color maps, this one fixes the intensity maps

### CODE REVIEW

**Comment by swalker2m** [comment]
I bet this has been broken since we made the OT an OSGi app. 👍

**Comment by cquiroz** [comment]
Exactly, the files come from the svn ocs1.5 repo

**Comment by arturog8m** [comment]
The fact that nobody has noticed this before really makes me think that the right solution to this problem is to remove this feature altogether....

**Comment by tpolecat** [comment]
I am always in favor of removing features, so 👍  to that.

**Pull request merged**
