### PR TITLE
REL-492: GMOS ITC warning when 4x spectral binning selected with IFU …

### PR DESCRIPTION
**Pull request by spakzad**
…mode.

Changes were only made to Gmos.java.

### CODE REVIEW

**Comment by cquiroz** [comment]
Looks fine, just a general question, why are there tabs `\t` in the warning, are they displayed to the user?

**Comment by spakzad** [comment]
Hi Carlos,
I was trying to add tabs to make it easier to read, but I see this is not appearing in the output.  I can take them out but they don't seem to do anything.

**Comment by cquiroz** [comment]
Right, that's what I thought. Would they appear on the web page? In html, tab really has no meaning, if you just mean spaces, you could put 4 spaces (or &nbsp; which is the representation for space)

**Comment by spakzad** [comment]
OK, I'll fix it and re-submit it.  Thanks!

**Comment by cquiroz** [comment]
the blank space was eaten in my comment,`&nbsp;` is normally the character used for a space in html. You could put for of those `&nbsp;&nbsp;&nbsp;&nbsp;` and should give you the same effect.

If you have fixes you can add them as new commits and update the Pull Request instead of closing, but closing is fine too

**Comment by spakzad** [comment]
I'm attaching a sample of what it looks like now.  Is it OK or should I take the extra spaces out?  If I do take them out, should I put everything on one line like the warning above this one?
rel492_sampleoutput

**Comment by andrewwstephens** [comment]
The current warning looks fine in the OT, although for consistency I would suggest using normal (not upper) case for the warning, and ending with a period since other warnings may come after this one.

warning

**Pull request closed without merging**
