### PR TITLE
Add hardened runtime option for codesigning

### PR DESCRIPTION
**Pull request by cquiroz**
This PR adds an option to the OSX signing stage to enable the "hardened runtime" option. It still needs testing

### CODE REVIEW

**Comment by swalker2m** [comment]
Seems fine. Does this work w/o updating the build machine?

**Comment by cquiroz** [comment]
yes it requires a new build machine

**Comment by swalker2m** [comment]
I think this is fine but maybe we should have the build machine updated before we merge it?

**Comment by cquiroz** [comment]
I guess I should close this one

**Pull request closed without merging**
