### PR TITLE
OCSADV-396-A: Draw selected targets on the TPE

### PR DESCRIPTION
**Pull request by cquiroz**
Sorry about the size of the PR, this started by attempting to plot targets from the new Catalog Query tool on the TPE and things started to unravel from there. The screenshot below shows the targets from the query tool plotted

screenshot 2015-10-23 16 24 19

The TPE is/was tightly integrated with the old CatalogNavigator, making it not possible to just slap-in the new one. A simple attempt to get plotting work broke at least the following functionality:

- Zoom In/Out
- OT Browser
- Image Loading
- GeMS Manual Search
- Pick Objects
- Probably many more yet to be found...

A much larger refactoring was then required and big chunks on unused code have been removed and adapted to work with the Query Tool.

The OT Browser had to be adapted removing the surrounding menu/toolbar:
screenshot 2015-10-23 16 37 13

 Know still broken are:

- Pick Objects
- Save Catalog Table Overlays...
- GeMS manual search zooming

The PR  also contains a fix for REL-2507 about targets not displayed on the GeMS Manual Search mode

I don't expect people to check this PR as it is just too large and most of it is just refactoring and deletion of TPE Code, but it marks a checkpoint for a test release to keep testing the functionality

### CODE REVIEW

**Comment by fnussber** [comment]
Lots of code cleanup. Nice. I went through about half the commits, all seems to make sense. I fully trust you to know what you're doing and I guess Andy is aware that the new Catalog Query Tool will need a lot of testing. :+1:

**Comment by cquiroz** [comment]
Good to hear, it feels like I undid half of the commits on the other half :smile: But you cannot go wrong deleting a few thousands lines of code
We'll postpone merging until more testing is done, Andy already found a few bugs

**Comment by cquiroz** [comment]
Added fixes for OCSADV-451, OCSADV-449 and OCSADV-452

OCSADV-452 (Restored menu)
screenshot 2015-10-26 17 44 22

OCSADV-449: (Added Save As menu)
screenshot 2015-10-26 18 55 52

**Comment by cquiroz** [comment]
More commits to fix OCSADV-454, OCSADV-455 and OCSADV-456, The TPE can indicate now the guiding quality on the plots:

screenshot 2015-10-27 17 29 14

**Comment by cquiroz** [comment]
Added fixes for OCSDAV-459, OCSADV-460, OCSADV-462

**Comment by cquiroz** [comment]
Added more code to fix a bug on OCSADV-460, OCSADV-464 and OCSADV-463

**Comment by cquiroz** [comment]
Added fixes for OCSADV-467, OCSADV-466, OCSADV-465 plus deletion of legacy unused classes

**Comment by cquiroz** [comment]
Merged the branch with the updated OT Browser (OCSADV-450) completely separated from the old Catalog Navigator and with a few small UI touches

screenshot 2015-11-01 22 31 12

**Comment by cquiroz** [comment]
Added fixes for OCSADV-421, OCSADV-476, OCSADV-477, OCSADV-478, OCSADV-479 and  OCSADV-416

**Comment by cquiroz** [comment]
Added fixes for OCSADV-471 and OCSADV-483

**Comment by cquiroz** [comment]
All my changes are in, we are merged with develop and all tests pass, I'll wait a bit for possible comments and then merge

**Pull request merged**
