### PR TITLE
REL-2408: Updated F2 template XML

### PR DESCRIPTION
**Pull request by sraaphorst**
This is an update the the F2 template XML as per Ruben and Andy.
The tests listed in the JIRA issue seem to pass correctly with the new template in place.

### CODE REVIEW

**Comment by cquiroz** [comment]
Did you verify the tests manually?

**Comment by sraaphorst** [comment]
@cquiroz 
I hope I did it right. I created an F2 observation in the PIT, imported it using the skeleton script into my locally running ODB / spdb, and then opened it in the OT to ensure that the two ARCs they mentioned appeared, one in each of the the telluric observations.

Does that seem right? I am still somewhat new to working with templates.

**Comment by cquiroz** [comment]
That sounds right. @tpolecat did some automated tests for the templates but they seem to be hard to implement. Manual tests are normally enough

**Comment by cquiroz** [comment]
:+1:

**Comment by sraaphorst** [comment]
Thanks for confirming that what I did seems correct :-). Much appreciated! I'm going to merge, then.

**Pull request merged**
