### PR TITLE
REL-3851: Update user icons, splash screen.

### PR DESCRIPTION
**Pull request by sraaphorst**

### CODE REVIEW

**Comment by cquiroz** [comment]
Didn't we use the jupiter image already some years ago?

**Comment by sraaphorst** [comment]
@cquiroz It was a slightly different one:
Screen Shot 2020-10-16 at 11 15 19 AM

**Comment by sraaphorst** [comment]
I think the newer one is being used because as per the splash screen text, it's the highest quality infrared image of Jupiter from a ground-based telescope.

**Review by cquiroz — APPROVED** [review]
LGTM

**Pull request merged**
