### PR TITLE
REL-2280 Updated QPT icons

### PR DESCRIPTION
**Pull request by cquiroz**
Updated QPT icons to match the OT and PIT

### CODE REVIEW

**Comment by fnussber** [comment]
I guess :+1:

**Comment by swalker2m** [comment]
When I look at the `.icns` file in Preview, there are progressively smaller sizes from 1 (the biggest) down to 9 (the smallest).  Forgive my ignorance but for some reason the images at positions 6 and 9 look odd.  Like maybe a map or horse running (is this a Rorschach test?).  If these images are indeed corrupt in some way, it seems like it could impact scaling.

**Comment by swalker2m** [comment]
images6and9

**Comment by swalker2m** [comment]
Not to mention they say "PIT" instead of "QPT".

**Comment by cquiroz** [comment]
Thanks for noticing those problems, now they should be ok

**Comment by swalker2m** [comment]
Icons look good but it somehow pulled in @tpolecat's changes.

**Comment by cquiroz** [comment]
A rebase fixes that :D

**Comment by swalker2m** [comment]
Excellent. :+1:

**Pull request merged**
