### PR TITLE
trying out sbt -q

### PR DESCRIPTION
**Pull request by tpolecat**
This may or may not confuse Travis. We shall see.

### CODE REVIEW

**Comment by cquiroz** [comment]
What does the `-q` do? I couldn't find sbt command line options documentation

**Comment by tpolecat** [comment]
@cquiroz I recommend using [sbt-extras](https://github.com/paulp/sbt-extras) which has a useful `-help` menu and other things. This is what Travis provides.

**Comment by swalker2m** [comment]
D'oh:

Timeout (20 minutes) reached. Terminating "sbt -q test:compile test"
The command sbt -q test:compile test exited with 137.

**Comment by cquiroz** [comment]
I think that is because travis expects some output
if it doesn't get anything in some timeout it thinks the process is dead. Maybe a warning level would be better

**Comment by tpolecat** [comment]
Trying again with a 40 minute timeout.

**Comment by swalker2m** [comment]
Interesting though that when it did fail with the timeout, it seemed to dump the entire log anyway?  If that happens on a test case failure then `-q` won't be that helpful.

**Comment by tpolecat** [comment]
Yeah that's puzzling. They may not work together.

**Pull request closed without merging**
