### PR TITLE
Add command to open dash from sbt prompt

### PR DESCRIPTION
**Pull request by tpolecat**
I find myself looking stuff up a lot in Dash and it's kind of clicky. So this lets you do it from the sbt prompt.

### CODE REVIEW

**Comment by swalker2m** [comment]
Two thumbs up.  :+1: :+1: How did you get the scalaz docset, btw?  Generating it from mkscaladocset looks annoying.

**Comment by tpolecat** [comment]
You can generate a docset from anything on Maven Central; it downloads and converts the doc jar. So go to **Preferences > Downloads > Scala Docsets**, search for `scalaz` and then select `org.scalaz:scalaz_2.11 7.1.0` and it will  generate the docset. Takes a minute or two. If you don't see this option you may need to update Dash.

**Comment by swalker2m** [comment]
Excellent, got it.

**Comment by swalker2m** [comment]
Note there's also an Idea Dash plugin which lets you highlight something and do a Dash search.  I had to reassign the keyboard shortcut but otherwise it seems to work.

**Pull request merged**
