### PR TITLE
Feature/REL-3680 - change ITC html links to be relative

### PR DESCRIPTION
**Pull request by andrewwstephens**
This changes the ITC web page output links to be relative instead of absolute to help fix a problem displaying images to users outside of Gemini.

For simple changes like this is it preferred to comment or remove the unwanted code?

### CODE REVIEW

**Comment by cquiroz** [comment]
Why would this change affect the baseline?

**Comment by andrewwstephens** [comment]
They all failed after this change, so perhaps the tests compare the raw HTML output?

**Comment by andrewwstephens** [comment]
This changes the HTML output from something like this:

```
<img alt="Signal/Background Chart" src="http://itc.gemini.edu:9080/itc/servlet/images?type=img&filename=SignalChart&chartIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"/><br><br>
<a href ="http://itc.gemini.edu:9080/itc/servlet/images?type=txt&filename=SignalData&chartIndex=0&seriesIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"> Click here for ASCII signal spectrum.</a><br>
<a href ="http://itc.gemini.edu:9080/itc/servlet/images?type=txt&filename=BackgroundData&chartIndex=0&seriesIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"> Click here for ASCII background spectrum.</a><br>
<img alt="Signal to Noise Chart" src="http://itc.gemini.edu:9080/itc/servlet/images?type=img&filename=S2NChart&chartIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"/><br><br>
<a href ="http://itc.gemini.edu:9080/itc/servlet/images?type=txt&filename=SingleS2NData&chartIndex=0&seriesIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"> Click here for Single Exposure S/N ASCII data.</a><br>
<a href ="http://itc.gemini.edu:9080/itc/servlet/images?type=txt&filename=FinalS2NData&chartIndex=0&seriesIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"> Click here for Final S/N ASCII data.</a><br>
```

to this:

```
<img alt="Signal/Background Chart" src="/itc/servlet/images?type=img&filename=SignalChart&chartIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"/><br><br>
<a href ="/itc/servlet/images?type=txt&filename=SignalData&chartIndex=0&seriesIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"> Click here for ASCII signal spectrum.</a><br>
<a href ="/itc/servlet/images?type=txt&filename=BackgroundData&chartIndex=0&seriesIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"> Click here for ASCII background spectrum.</a><br>
<img alt="Signal to Noise Chart" src="/itc/servlet/images?type=img&filename=S2NChart&chartIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"/><br><br>
<a href ="/itc/servlet/images?type=txt&filename=SingleS2NData&chartIndex=0&seriesIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"> Click here for Single Exposure S/N ASCII data.</a><br>
<a href ="/itc/servlet/images?type=txt&filename=FinalS2NData&chartIndex=0&seriesIndex=0&id=4637f01c-bf47-4331-add9-4f667467d5fa"> Click here for Final S/N ASCII data.</a><br>
```

**Comment by cquiroz** [comment]
It is a pity that we have to change these in an urgency due to unannounced upstream changes at the border
Regardless, the code change looks

**Pull request merged**
