### PR TITLE
REL-3120: Cleanup of jsky.app.ot.gemini package.

### PR DESCRIPTION
**Pull request by sraaphorst**
This eliminates the unused classes and some comment cruft from this package.

### CODE REVIEW

**Comment by arturog8m** [comment]
it's nice to get rid of all this unused code. Just to confirm: Did you manually check all the instrument editors (especially NIFS and NIRI) to confirm they continue working? I'm always afraid of being hit by reflection.

**Comment by sraaphorst** [comment]
Yes, I instantiated all the instruments in a test program and went through to make sure they are working since we got bitten by reflection once before in code elimination :-).

**Comment by cquiroz** [comment]
once?

**Comment by sraaphorst** [comment]
😆  I'm sure it's happened multiple times, but one instance sticks out in particular.
I think I have psychologically blotted out the rest.

Note that these `...GUI` classes all have `...Form` class equivalents with which they have been replaced.

**Pull request merged**
