### PR TITLE
Merge branch 'release/ocs-2015A.1.2' into develop

### PR DESCRIPTION
**Pull request by cquiroz**
This PR contains the changes resulting of merging the release branch into develop. There were many conflicts that were resolved by hand.
The whole project compiles and tests compile too but not all tests were executed

the following files were in conflict during the merge:
bundle/edu.gemini.ags/src/main/java/edu/gemini/ags/impl/RadiusLimitCalc.java
bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsAnalysis.scala
bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/conf/ProbeLimitsParser.scala
bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/conf/package.scala
bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsMagnitudeTable.scala
bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala
bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategyParams.scala
bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/ags/AgsAnalysisRule.scala
bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2OiwfsGuideProbe.java
bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosOiwfsGuideProbe.java
bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/GnirsOiwfsGuideProbe.java
bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nici/NiciOiwfsGuideProbe.java
bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nifs/NifsOiwfsGuideProbe.java
bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/niri/NiriOiwfsGuideProbe.java
bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/guide/GuideProbeUtil.java
bundle/edu.gemini.qpt.client/src/main/scala/edu/gemini/qpt/core/listeners/AgsAnalysisListener.scala
bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/AbstractTelescopePosEditor.java
bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/SiderealEditor.java
bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TelescopePosEditor.java
bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/GuidingFeedback.scala
project/src/main/scala/edu/gemini/osgi/tools/app/RPMDistHandler.scala

### CODE REVIEW

**Comment by swalker2m** [comment]
Could the people involved in editing any of these files, which I think would be @sraaphorst and @tpolecat for the most part, take a quick sanity-check look?

As @cquiroz says, we should get this merged in first and then rebase the other existing PRs.

**Comment by sraaphorst** [comment]
I checked out the code that I've touched that this deals with, and it looks :+1: to me.
Did we also want @fnussber to look at this since it seems to touch QV code in some places?

**Comment by swalker2m** [comment]
Re: @fnussber:  always welcome but fortunately I don't think there were any conflicts in the QV stuff.

**Comment by tpolecat** [comment]
There was a 1-line change that affects me. Not a big deal.

@cquiroz what did you mean that "not all tests were executed"?

**Comment by cquiroz** [comment]
It means, the tests compiled and I started to execute the tests but I get an OOM after a while when doing so, perhaps I need to update my sbt settings

**Comment by swalker2m** [comment]
This is what I'm using, for what it's worth:

````
$ echo $SBT_OPTS 
-XX:ReservedCodeCacheSize=256M -XX:MaxPermSize=256M -Xmx3500M -Xss2M -Dfile.encoding=UTF-8
````

**Comment by tpolecat** [comment]
Yes, I use the following with `sbt-extras` ... if you're not using this you may need to set a different environment variable (`SBT_OPTS` maybe?)

```
export JVM_OPTS='-Dfile.encoding=UTF-8 -XX:MaxPermSize=1024m -Xms512m -Xmx3500m -Xss2m -XX:ReservedCodeCacheSize=256m -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC'
```

**Comment by cquiroz** [comment]
With the sbt options I get all the tests to pass, except a minor one related to the new PIT release, I'd rather fix that directly on **release/pit-2015B.2.1**

**Pull request merged**
