### PR TITLE
SEQNG-776: add planned time to seqexec sequence data

### PR DESCRIPTION
**Pull request by swalker2m**
Updates the `SeqExecService` used by the seqexec to replace the sequence with `PlannedTime`.  `PlannedTime` contains the sequence in addition to the time estimations requested by this task.  You can extract the sequence from the `PlannedTime` instance with `plannedTime.sequence`.

### CODE REVIEW

**Comment by cquiroz** [comment]
Will this compile with scala 2.12?

**Comment by swalker2m** [comment]
So this should work, but I'm not sure we should do it.  It will complicate migration to the new sequence and new codebase because we don't have planned time estimates there.  Can we push back on this task?

**Comment by cquiroz** [comment]
Is this change required to implement estimation of sequence time on the new seqexec?

**Comment by tpolecat** [comment]
> Will this compile with scala 2.12?

Yes, the `left`/`right` projections on `Either` still work.

**Comment by swalker2m** [comment]
I'm going to go ahead and shelve this PR since we agreed it would delay migration to the new ODB.

**Pull request closed without merging**
