### PR TITLE
REL-566: ignore acquisition and cal for ToO triggers

### PR DESCRIPTION
**Pull request by swalker2m**
This PR updates the development branch for the REL-566 changes to the release branch.

### CODE REVIEW

**Comment by swalker2m** [comment]
Hmm, tests pass just fine locally and in the release branch with these same changes.

**Comment by tpolecat** [comment]
Did you find the failure in the log? We really do need to crank that down.

**Comment by cquiroz** [comment]
I  see a bundle_edu_gemini_spModel_io/test sbt.TestsFailedException

**Comment by swalker2m** [comment]
Rebased, restarted and now the tests pass.  Confidence high.

**Pull request merged**
