### PR TITLE
REL-1371: added line to find AO FWHM for Uniform source

### PR DESCRIPTION
**Pull request by leashma**
Closed old pull request and made a new one. Changes for a different branch were accidentally incorporated in this one, and not testable yet. this branch tested and passed all local tests. Ready for merging tests.

### CODE REVIEW

**Comment by leashma** [comment]
Is there anything I need to do to fix this so the check can pass? I don't understand if the Travis CI build was my fault or not.

**Comment by sraaphorst** [comment]
@leashma It's not your fault. I needed to fix a Travis configuration issue, which is now repaired.

**Comment by sraaphorst** [comment]
I need to update this so that it passes: I'm going to create another PR with your changes that has the updated Travis config file instead of trying to figure out how to update your PR myself.

**Comment by sraaphorst** [comment]
Instead done here:
https://github.com/gemini-hlsw/ocs/pull/1666

**Pull request closed without merging**
