### PR TITLE
OCSADV-208: Cleaning out obsolete/unused stuff.

### PR DESCRIPTION
**Pull request by fnussber**
A first clean sweep that mainly removes obsolete, deprecated and unused stuff: 35 java files and 70 data files have been eliminated in that process. Also got rid of (copy-pasted) Altair support for F2 and integrated the last remaining changes from the SVN repository.

### CODE REVIEW

**Comment by cquiroz** [comment]
This must be a new record -726035. Congratulations!

**Comment by fnussber** [comment]
:)

**Comment by swalker2m** [comment]
Wow, nice job.  I'm not going to go through all of that but, :+1: :+1:  

BTW, I'm pretty sure I've never even seen these files yet they mostly have stuff like: `$Id: ColorFilter.java,v 1.3 2003/11/21 14:31:02 shane Exp $` at the top. :-/

**Comment by tpolecat** [comment]
Holy crap.

**Comment by tpolecat** [comment]
And by that I mean :+1:

**Pull request merged**
