### PR TITLE
OCSADV-276: Implemented execution state memory, sequence execution co…

### PR DESCRIPTION
**Pull request by jluhrs**
Sequences commands: start, stop, continue, getExecutionState. I share the blame with Rob for this code, although it's easy to find who wrote what (tip: the horrible parts are probably mine)

### CODE REVIEW

**Comment by tpolecat** [comment]
Cool! I'll give this a close look.

**Comment by jluhrs** [comment]
Modified the code so that instead of passing around the AtomicReference used to save the execution state (which is an implementation detail), now I pass the function that will save the state.

**Comment by cquiroz** [comment]
I've tried to read this PR but it seems my knowledge of scalaz is not enough to follow it. While the comments are certainly useful and give a good indication of what's going, I was not able to follow the details of the implementation.
Perhaps pointers to documentation on the relevant concepts would be useful or we might organize a presentation to go over the details.

**Comment by tpolecat** [comment]
Yeah I will read this in detail today. Sorry for the delay.

**Comment by tpolecat** [comment]
@jluhrs can you separate out the impure methods on `Executor`, perhaps by making `Executor` into a trait and implementing it as `object ExecutorImpl` or something? Also please mark the impure methods with `unsafe` (as in `unsafeStartCmd`)? It will be much easier to follow that way I think.

**Comment by tpolecat** [comment]
:-1: there are some issues with the state management effects. I will add a longer comment. Hold off for now.

**Comment by tpolecat** [comment]
@jluhrs  I made a PR to your branch with some suggested changes.

**Comment by jluhrs** [comment]
I just merged Rob's suggestions.

**Comment by tpolecat** [comment]
Ok if it's working to your satisfaction then :+1:

**Pull request merged**
