### PR TITLE
REL-3653: Updating OT and PIT icons for 2019B.

### PR DESCRIPTION
**Pull request by sraaphorst**

### CODE REVIEW

**Comment by cquiroz** [comment]
Why are files being deleted? like the `ico` files? Shouldn't they be updated?

**Comment by sraaphorst** [comment]
Well, I apparently somehow mangled that terribly. No idea how I managed that. 😾
Sorry, @cquiroz 

I'll try again tomorrow morning.

**Comment by sraaphorst** [comment]
Wait... never mind. The files were not deleted: they've just shrunk in size.

We both misinterpreted that. Looks like the build failure is an apt thing.

**Comment by sraaphorst** [comment]
@cquiroz This finally passed all tests. Can you 👍 it?

**Pull request merged**
