### PR TITLE
Squants update

### PR DESCRIPTION
**Pull request by cquiroz**
This PR updates the OCS to use the latest squants release containing our latest PRs. This release also has OSGi support meaning it can be used as a managed dependency

SPDB, OT and ITC that use squants were tested

### CODE REVIEW

**Comment by cquiroz** [comment]
I'm piggybacking this PR to remove unused spdb configurations that just slow down the build

**Comment by tpolecat** [comment]
Looks great, thanks! 👍

**Comment by cquiroz** [comment]
I will wait for the release to merge this, just in case 😄

**Comment by swalker2m** [comment]
There's a release branch now, `release/ocs-2016B`, so we may as well merge this finally.

**Pull request merged**
