### PR TITLE
REL-3100: Migrating PIT Horizons changes to develop.

### PR DESCRIPTION
**Pull request by sraaphorst**
Finally, the last PR for this never-ending REL task.

### CODE REVIEW

**Comment by tpolecat** [comment]
Did you cherry-pick the commits from the release branch or copy the changed files over and re-commit them, or what? It's not immediately obvious that these are the same changes but they do look the same.

**Comment by sraaphorst** [comment]
@tpolecat I actually just copied the changed files over.

This is probably an incredibly stupid way to do things, as I'm sure there's a far more efficient way to do this, but I'm not certain what it is. I need to sit down and spend more time learning the finer points of git.

**Comment by tpolecat** [comment]
Ok this is fine. For reference, `git cherry-pick <commit>` will add an existing commit to the working branch.

**Comment by sraaphorst** [comment]
Thanks, @tpolecat. That's excellent to know and will save me a lot of time and irritation if something like this comes up again!

**Pull request merged**
