### PR TITLE
REL-2287: Do not allow proposal submission without the full PI name

### PR DESCRIPTION
**Pull request by cquiroz**
Per user request the initial name of the PI is set to 'Principal Investigator'. This will generate an error asking the user to set the real name

### CODE REVIEW

**Comment by swalker2m** [comment]
Where is the error is detected?  :+1:

**Comment by cquiroz** [comment]
The error is handled on the `ProblemRobot` class and will show on the Problems section:
screenshot 2015-06-23 15 06 14

**Comment by arturog8m** [comment]
I think the "Please provide PI's full name" should be a TODO rather than an error, to be consistent with everything else.

**Comment by cquiroz** [comment]
I tend to agree, I'll check with Andy

**Comment by cquiroz** [comment]
Updated to show a ToDo instead of Error
screenshot 2015-06-23 16 28 25

**Comment by arturog8m** [comment]
Nice :+1:

**Pull request merged**
