### PR TITLE
Retrofit REL-2841/REL-2853

### PR DESCRIPTION
**Pull request by cquiroz**
This PR brings three pull requests into ocs-2016B, these already exist on develop

### CODE REVIEW

**Comment by swalker2m** [comment]
Is the squants update needed for one of the other two items?

**Comment by cquiroz** [comment]
No, we could do away with that if you think is best

**Comment by swalker2m** [comment]
I guess if possible we should limit changes unless they are small, low-risk and fixing some bug.  So if the squants update isn't required, it might be best to wait for the December release so it can be part of the regular testing cycle.

**Comment by cquiroz** [comment]
Ok, it has been removed

**Comment by arturog8m** [comment]
Thanks, I agree. We should limit the changes for the patch release as testing time is fairly limited and we want to keep it focused.

**Comment by swalker2m** [comment]
👍

**Pull request merged**
