### PR TITLE
REL-3228: Put the ITC conditions frequency of occurrence in bold face

### PR DESCRIPTION
**Pull request by leashma**
Based on a comment from Bryan, I also changed the syntax from "frequency of occurrence" to "likelihood of execution."

### CODE REVIEW

**Comment by cquiroz** [comment]
This is on hold until the baseline is updated since this change breaks the tests
if this is urgent i can do the baseline update myself

**Comment by leashma** [comment]
[baseline.txt](https://github.com/gemini-hlsw/ocs/files/1416183/baseline.txt)

Attached new baseline.txt file. Changes compile okay, but when I ran tests, this was the output for every instrument calculator:

[info] TRecs calculations should
[error]   x match latest baseline
[error]    Falsified after 0 passed tests.
[error]    > ARG_0: Fixture(TRecsParameters(N (broad 10um),KBr,High Res Grating,12.0 µm,Slit 0.21 arcsec),SourceDefinition(UniformSource,EmissionLine(12.8 µm,500.0 km/s,5.0E-19 W/m²,1.0E-16 W/m²/µm),12.0,Vega,N,Redshift(1.5)),ObservationDetails(SpectroscopyS2N(6,300.0,1.0),UserAperture(2.5,6.0)),ObservingConditions(IQ20,CC50,WV50,SB50,1.5),edu.gemini.itc.shared.TelescopeDetails@5e9bd2f1,PlotMethod:	AUTO
[error]    PlotLowerLimit:	0.3
[error]    PlotUpperLimit:	0.6
[error]    
[error]    )
[error]    > false (file:1)

**Comment by cquiroz** [comment]
I uploaded a new baseline. Finding the correct one is a bit tricky that's why the one you sent still fails. Took me a while to realize they are written to the target dir not to the original dir

**Comment by tpolecat** [comment]
@cquiroz are you logged in as admin?

image

**Comment by cquiroz** [comment]
hmm interesting

**Comment by sraaphorst** [comment]
I've irritatingly had the exact same thing happen to me on two occasions.
I think I had to zap my local git credentials and log back in.

**Comment by cquiroz** [comment]
i guess the issue here is that I'm commiting to @leashma 's PR, i'm not sure I can rewrite history

**Comment by tpolecat** [comment]
You can reset to before any of this happened and re-commit as you and force-push.

My concern is really that nobody should ever be logged in as that user. Are there some tasks that require it? I have never been anyone other than me.

**Comment by cquiroz** [comment]
I used it to add tags, i think you need to do that as admin

**Comment by cquiroz** [comment]
Well the last commit shows under my name. I'm not sure why the email had `admin`

**Comment by leashma** [comment]
Can you be more explicit about where to update the baseline so I can make sure to do this correctly in the future? I added a new one in the comments, and followed these steps to update it:

# If test fail, update ITC baseline:
1. comment out the @Ignore before BaselineTest.create() in BaselineTest.scala
2. sbt> test-only edu.gemini.itc.web.baseline.BaselineTest
3. cp /Desktop/ashugart/ocs/ocs/bundle/edu.gemini.itc.web/target/scala-2.11/test-classes/baseline.txt
   to /Desktop/ashugart/ocs/ocs/bundle/edu.gemini.itc.web/src/test/resources/baseline.txt
4. reinstate the @Ignore
5. sbt> test

**Comment by cquiroz** [comment]
It is the step 3. at least that confused me

**Comment by cquiroz** [comment]
@tpolecat Do you see a problem merging like this. I see the commit under `cquiroz`

**Comment by sraaphorst** [comment]
I see the commit as @cquiroz as well. I'm going to approve this so that we can go ahead with the build.

**Comment by cquiroz** [comment]
@sraaphorst and I have convinced ourselves that the commit is fine.

```
git show --format=fuller
commit fe34897fb86f88dc74bf1bed94ceb12d02ef5ec2 (HEAD -> feature/REL-3228, leashma/feature/REL-3228)
Author:     Carlos Quiroz <cquiroz@gemini.edu>
AuthorDate: Thu Oct 26 11:21:04 2017 -0300
Commit:     Carlos Quiroz <cquiroz@gemini.edu>
CommitDate: Thu Oct 26 12:03:03 2017 -0300

    Updated baseline
```

I'll merge

**Comment by arturog8m** [comment]
@cquiroz could you confirm that @leashma procedure is the correct one to follow?

**Pull request merged**
