### PR TITLE
OCSADV-155: Replace PIT target model

### PR DESCRIPTION
**Pull request by cquiroz**
This is the first PR on the process to port the PIT target model with the new model on `spModel.core`
In this PR the phase1 immutable `Magnitude`, `MagnitudeBand` and `MagnitudeSystem` classes are removed and the new classes are used.
The change itself is relatively simple but impacts several parts of the OCS which are converted and tested:

* PIT
* PIT Target importer
* Phase2 Skeleton servlet/factory
* ITAC

A next step is to port Coordinates-related classes

### CODE REVIEW

**Comment by swalker2m** [comment]
The code looks fine to me but I'm wondering about the schema and the import / export, etc.  `Target.xsd` will still define `Magnitude` and `MagnitudeBand`?  Are there still mutable types for these etc.?

**Comment by swalker2m** [comment]
Also, what impact is there (if any) on ITAC?

**Comment by cquiroz** [comment]
There are mutable types for those, they are generated by JAXB out of the schema, they are needed when we move to the immutable model, in this case from `spModel.core`. The mutable classes are also used by ITAC

In response to the second question, ITAC uses the mutable model directly, being it more Java friendly than the immutable. ITAC was built against the new model and it seems fine, I tested imports, queue creation, web interfaces, exports, etc

**Comment by swalker2m** [comment]
Should the bands continue to be defined in the schema?  If not, I suppose it complicates validation?

**Comment by swalker2m** [comment]
:+1:

**Comment by cquiroz** [comment]
Good question, there is a subset of allowed bands on the p1 schema, I'll check with Andy

**Comment by cquiroz** [comment]
About bands, the missing bands are the SDSS and they should be fixed as part of REL-2352

**Pull request merged**
