### PR TITLE
REL-3360: Added Alopeke code to template generator.

### PR DESCRIPTION
**Pull request by sraaphorst**
This adds the basics of the `Alopeke` code to the template generator so that P1 proposals from ITAC can be imported into the ODB.

### CODE REVIEW

**Comment by swalker2m** [comment]
Were you able to import an Alopeke proposal into the ODB?

**Comment by sraaphorst** [comment]
@swalker2m Yes. I should have posted the process. Here is an Alopeke P1 proposal:
screen shot 2018-03-29 at 10 20 02 am

I followed this up by:

`skeleton alopeke.xml alopeke.pdf GN-2108B-Q-1`

or something to that extent, which gave:

screen shot 2018-03-29 at 10 19 05 am

And finally:

screen shot 2018-03-29 at 10 19 49 am

**Comment by swalker2m** [comment]
Looks good, but should the name field in the OT be a lot wider?  It looks like it is cutting off a lot of information in order to align with the numeric fields below it.

**Comment by sraaphorst** [comment]
Yes, let's make it wider. I'll fiddle with that now.

**Comment by andrewwstephens** [comment]
It's not that important, so let's go with that for now.

**Comment by sraaphorst** [comment]
I went and fixed the field lengths since this was easy:
screen shot 2018-04-02 at 10 47 08 am

**Pull request merged**
