### PR TITLE
Revert "REL-2185: Other type programs are now selected by default"

### PR DESCRIPTION
**Pull request by sraaphorst**
Reverts gemini-hlsw/ocs#1376

### CODE REVIEW

**Comment by cquiroz** [comment]
Why are you reverting?

**Comment by swalker2m** [comment]
I'm not sure I understand, this change was made to the development branch though?  There should be a release branch for things that we want to change to the production version.

**Comment by arturog8m** [comment]
#1378 takes care of the production version. This takes cares of the development branch - this feature needs to be reviewed before implementing it.

**Comment by sraaphorst** [comment]
Sorry for jumping the gun on this. I think I got eager and misread Andy's email as saying to go ahead when I should have waited for full clarification. Looks like Travis is complaining so I'll rerun.

**Pull request merged**
