### PR TITLE
REL-2906: Updated F2 templates for 2017A

### PR DESCRIPTION
**Pull request by cquiroz**
Small changes to the phase2 template for F2

### CODE REVIEW

**Comment by cquiroz** [comment]
I didn't add a test since this PR removes a feature (darks) from the template. I guess it is worth to add a test confirming that no darks are added

**Comment by cquiroz** [comment]
Added test as suggested

**Comment by tpolecat** [comment]
👍 Thanks! The template expansion stuff has so much machinery it's just kind of reassuring to see a test in there.

**Comment by cquiroz** [comment]
It has been a source of hard to track bugs in the past, so yes tests are nice!

**Pull request merged**
