### PR TITLE
Turn off PollServiceSpec tests.

### PR DESCRIPTION
**Pull request by swalker2m**
Skips `PollServiceSpec` tests since they cannot run reliably in travis.

### CODE REVIEW

**Comment by cquiroz** [comment]
I'd argue that if a test cannot run reliably because the hardware is perhaps too slow, the test should be changed to run in that environment rather than just be ignored
We probably have a bunch of tests that have that kind of timeouts built it

**Comment by swalker2m** [comment]
The problem is that there is no good answer for how long an operation should "usually" take.  If I increase the timeouts to ridiculous values then the test phase of the build will, corresponding, take ridiculously longer to finish.

**Comment by cquiroz** [comment]
Yes, it is difficult to tell how long to wait, is it talking to a remote service?
Short of rethinking the whole test I think is ok to have a longer timeout considering the (presummably) slower hardware

**Comment by swalker2m** [comment]
@cquiroz I looked closely at the tests and found that really only one couldn't be fixed with a ridiculously long timeout.  The others should still terminate long before the timeout, presumably.  So I increased the timeout considerably and was able, I think, to change the problematic test to make it work in this environment.  Thanks for the pushback.  In the end the `PollServiceSpec` is not only still viable but also better than it was.  That's my hope anyway.  We'll see what verdict Travis renders.

**Comment by cquiroz** [comment]
Travis agrees with you :+1:

**Pull request merged**
