### PR TITLE
REL-3997: GHOST TPE Fibers

### PR DESCRIPTION
**Pull request by swalker2m**
General GHOST TPE update:

* Displays HR sky fibers
* Shows IFUs used for sky positions in a blue-ish color instead of green
* Shows labels on the IFUs when the size is big enough to permit seeing them

Since I couldn't find requirements that I could understand I made up my own.  Accordingly, expect iteration on this.

Screen Shot 2021-11-05 at 10 32 01

### CODE REVIEW

**Review by tpolecat — APPROVED** [review]
:+1: It would be cool to see a screenshot if you have one.

**Comment by swalker2m** [comment]
Standard Resolution, Dual Target. Dedicated sky fibers in blue.

Screen Shot 2021-11-05 at 14 28 21

**Comment by swalker2m** [comment]
Standard Resolution, Target + Sky.  S2 (SRIFU2) shown in blue since it is placed at a sky coordinate.
Screen Shot 2021-11-05 at 14 32 58

**Comment by swalker2m** [comment]
High Resolution, Target + Sky.  "H" for HRIFU.  Here the SRIFU2 (S2) is also used for sky and you can see the dedicated HR sky fibers above it.

Screen Shot 2021-11-05 at 14 37 33

**Comment by tpolecat** [comment]
Neato. Very nice.

**Pull request merged**
