### PR TITLE
REL-2858: Add PA mode option to GSAOI component

### PR DESCRIPTION
**Pull request by cquiroz**
This PR includes:

* Changes GSAOI model to include a flag for position angle constraints
* Update Gsaoi Editor to with the new flag
* Changes GEMS-AGS algorithm to select position angles depending on the flag
* Updates Gems Manual Search Dialog box to sync the old pos angle constraint flag with the model. The sync is two way between both editors

screenshot 2016-07-11 13 47 03

screenshot 2016-07-11 13 48 35

### CODE REVIEW

**Comment by andrewwstephens** [comment]
Could we change the label to say "Adjust PA to find optimal guide stars" and move it under the "Pos Angle" field ?

**Comment by bryanmiller** [comment]
I suggest the following layout on the GSAOI component
Position Angle |___0.0_| deg E of N   [ ] Allow Auto Guide Search to select PA    
put it on two lines if necessary
Position Angle-------------
 |___0.0_| deg E of N   [ ] Allow Auto Guide Search to select PA    
so that it is similar to the GMOS component.

**Comment by cquiroz** [comment]
What about this:

screenshot 2016-07-11 15 07 07

**Comment by swalker2m** [comment]
Code and screen shots look good to me.  👍 We can fiddle with the UI more after a test release if Bryan and/or Andy think it would be useful though.

**Pull request merged**
