### PR TITLE
remove slick

### PR DESCRIPTION
**Pull request by tpolecat**
This removes Slick from OCS.

### CODE REVIEW

**Comment by cquiroz** [comment]
Is it in any of the apps definitions?

**Comment by tpolecat** [comment]
I did a search and `slick` doesn't appear in any `.sbt`, `.scala`, or `.java` files so I think we're ok.

**Comment by tpolecat** [comment]
Hm where is Travis?

**Comment by cquiroz** [comment]
Hmm, good question, maybe it is waiting for #818 which is process?

**Comment by tpolecat** [comment]
@cquiroz ok that fixed it. I did a bunch of head resets and forced pushes so it managed to confuse travis/

**Comment by tpolecat** [comment]
Ok all green. Comments?

**Comment by cquiroz** [comment]
:+1:

**Pull request merged**
