### PR TITLE
REL-3865: Updated GRACES blueprint.

### PR DESCRIPTION
**Pull request by sraaphorst**
No changes need to be made to the import process, it seems.

### CODE REVIEW

**Review by cquiroz — APPROVED** [review]
LGTM

**Comment by swalker2m** [comment]
* The change is just that notes get added, correct?  No other logic changes?
* I think we should strip the scheduling blocks.

**Comment by sraaphorst** [comment]
@swalker2m According to the JIRA task, that appears to be the case. I'm not sure offhand how to strip the scheduling blocks but I'll take a look. (I'm also not sure why the checks failed here when all test cases passed locally. I'll look into it.)

**Comment by swalker2m** [comment]
> I think we should strip the scheduling blocks.

Ideally when we read the template database we could go through each observation and set the scheduling block to `None`. Alternatively we could just delete it from the XML for this case.

**Pull request merged**
