### PR TITLE
REL-4020: fixed position angle for MaroonX

### PR DESCRIPTION
**Pull request by swalker2m**
Fixes CR (and position angle) for MaroonX.

### CODE REVIEW

**Review by cquiroz — APPROVED** [review]
LGTM, all instruments should have a fixed PA

**Comment by swalker2m** [comment]
As it stands, this bit gets added to the `tcc_tcs_config_file` XML that gets sent to the TCC:
 
```
   <param name="posAngle" value="IPA0"/>
    <paramset name="IPA0" type="rotator">
      <param name="ipa" value="0"/>
      <param name="cosys" value="Fixed"/>
    </paramset>
```

Andy reports that the SOSs "select 'fixed' in the TCC menu", not `IPA0` as shown here.  It's unclear to me exactly what needs to be sent in order to satisfy the requirement from the task:

> The MAROON-X team confirms that all MAROON-X observations should have CR=Fixed, and it would be fine to hard-code that without modifying the Visitor Instrument interface.

**Comment by swalker2m** [comment]
Rotator config menu options:

CR_Config

"fixed" is selected for MaroonX apparently

**Comment by swalker2m** [comment]
Updated to

```
    <param name="posAngle" value="fixed"/>
    <paramset name="fixed" type="rotator">
      <param name="ipa" value="0"/>
      <param name="cosys" value="Fixed"/>
    </paramset>
```

per discussion with @jluhrs

**Pull request merged**
