### PR TITLE
REL-2464: change DSSI label

### PR DESCRIPTION
**Pull request by swalker2m**
A trivial change to the display name of DSSI in the PIT instrument list.

### CODE REVIEW

**Comment by sraaphorst** [comment]
Why was the PIT version renamed as 1.1.1? I was under the impression from discussions with Carlos that all PIT versions were always only two numbers (e.g. 1.1), hence the 0 in the third position.

**Comment by swalker2m** [comment]
I didn't know about the two-number convention, thanks for pointing that out!  I've changed it to 2016A.1.2.0.

It's a bit confusing because the version number actually *has* 3 digits and they all appear in the distribution files.  Nevertheless I see the app icon itself just says "Gemini PIT 2016A.1.1".  Perhaps you could update [the documentation](https://github.com/gemini-hlsw/ocs/wiki/Building-Phase-I-tools)?

**Comment by swalker2m** [comment]
Okay, it turns out that if you change the version number you have to update the ODB and probably ITAC.  I've returned to version 1.1.0 which is confusing since the app actually differs slightly, but we don't want to have to do an ODB update nor touch ITAC for this.

It would be useful to document this.  I put a placeholder in the [wiki page](https://github.com/gemini-hlsw/ocs/wiki/Building-Phase-I-tools#version-numbers) but someone who knows more should provide the information. ( @cquiroz  @sraaphorst ?)

**Comment by arturog8m** [comment]
I added REL-2475 so @cquiroz can update the documentation when he gets back. This should be merged :+1:

**Comment by cquiroz** [comment]
The pattern we agreed some time ago about versioning is year.semester.minor hence 2016.1.1 and decided to discard the last digit as we don't do PIT releases without changing the model.
About the change of DSSI I think it should produce a model change and we need to update the PDF templates and support upconversion. The change proposed will update the UI which may be enough for the users though
Was PIT 2016.1.1 released?

**Comment by bryanmiller** [comment]
Yes, PIT 2016A.1.1 is released.

**Comment by cquiroz** [comment]
Do we want to make an interim release for 2016A? If it is only a UI change I'd recommend keeping the current version otherwise it would mess the backends. If we need a full model change the we must switch to 2016A.1.2, update the backends and obsolete the previous client

**Comment by bryanmiller** [comment]
No, I don't think that we need an interim release. The current version is fine and I don't want to induce a lot of changes in other components.

**Pull request merged**
