### PR TITLE
Strip ephemeris data on export

### PR DESCRIPTION
**Pull request by swalker2m**
When we export a non sidereal observation to the seqexec, we include binary compressed ephemeris data.  Unfortunately the seqexec uses a newer Scala library and cannot read this information.  Fortunately, it also doesn't use this information and no other clients use this servlet.  I've modified the export to strip the ephemeris data and replace it with an empty map (since the codec requires something valid to be written there).

### CODE REVIEW

**Review by tpolecat — APPROVED** [review]
Ah shit, yeah that would do it. This must have been hard to figure out. So the seqexec can decode `Nil` but not the list elements themselves. Bah. 👍🏻

**Comment by swalker2m** [comment]
>  So the seqexec can decode Nil but not the list elements themselves. 

I'm not sure yet, Carlos is going to test it.  I may need to add a "catchingAll" `ParamSet` decoder or something :-/

**Comment by tpolecat** [comment]
They have taken some care to ensure that things like `Nil` and `None` always deserialize to their singletons, so it seems likely to work.

**Comment by cquiroz** [comment]
I was a bit surprised to notice that things like `Tuple3` don't have a `serialVersionID` thus I don't trust serialization promises 😄

**Comment by cquiroz** [comment]
🤯 🔫

**Comment by swalker2m** [comment]
Still doesn't work.  Serialization issues.  Closed in favor of #2252.

**Pull request closed without merging**
