### PR TITLE
REL-2197: AGS feedback for VisitorInstrument

### PR DESCRIPTION
**Pull request by sraaphorst**
Added a `VisitorRule` to force P2 AGS checks for visitor instruments.

Also removed the `UnknownError` I previously added and returned when the `Site` couldn't be determined since we don't want an obscure message of `Unknown error.` being displayed for AGS / P2 / QPT when this happens.

Made `AgsAnalysis` methods into `Option[AgsAnalysis]` methods to compensate for the removal to allow for no analysis when the analysis does not make sense / cannot be done.

### CODE REVIEW

**Comment by cquiroz** [comment]
I have modified the `AgsAnalysis` class as part of my porting work. When this PR is merged on develop there will be conflicts. I'm not sure what would be the best way to handle this
Any ideas?

**Comment by tpolecat** [comment]
@cquiroz you'll need to rebase and resolve the conflict before merging your PR.

**Comment by sraaphorst** [comment]
@cquiroz If you predict that the conflicts will be extensive, perhaps we can discuss the best way to handle this? Let me know.

**Comment by cquiroz** [comment]
I don't know how extensive but some of the signatures have changed to use `SideralTarget` instead of `SPtarget`. Since this PR is needed for the patch release we should likely go ahead and fix the conflicts when we merge into develop

**Comment by swalker2m** [comment]
Looks fine to me.  The pending conflict is unfortunate but I don't see a way around it. :+1:

**Pull request merged**
